export type Event = {
  id: number;
  type: string;
  desc1: string;
  desc2: string;
  address1: string;
  address2: string;
  month: string;
  date: string[];
  linkText: string;
  linkSrc: string;
  pic: string;
  color: string;
  lat: number;
  lng: number;
  isOpen: boolean;
  x: number;
  y: number;
  zIndex: number;
  isFull: boolean;
};
