export const eventsData = [
  {
    id: 1,
    type: 'Music',
    desc1: 'Joel',
    desc2: 'Macondo',
    address1: 'Le Marais',
    address2: '75011',
    month: 'septembre',
    date: ['2017', '09', '25'],
    linkText: 'www.gaite-lyrique.net',
    linkSrc: 'https://gaite-lyrique.net',
    pic: 'music.jpg',
    color: '#84a0fb',
    lat: 48.8566,
    lng: 2.3522,
    isOpen: false,
    x: 285,
    y: 100,
    zIndex: 2,
    isFull: false,
  },
  {
    id: 2,
    type: 'Food',
    desc1: '',
    desc2: '',
    address1: 'Petite Asie',
    address2: '75013',
    month: 'novembre',
    date: ['2017', '11', '03'],
    linkText: 'www.gaite-lyrique.net',
    linkSrc: 'https://gaite-lyrique.net',
    pic: 'food2.jpg',
    color: '#f3f3b9',
    lat: 48.83,
    lng: 2.3652,
    isOpen: false,
    x: 585,
    y: 400,
    zIndex: 1,
    isFull: false,
  },
  {
    id: 3,
    type: 'Arts',
    desc1: '',
    desc2: '',
    address1: 'La Chappelle',
    address2: '75010',
    month: 'janvier',
    date: ['2018', '01', '07'],
    linkText: 'www.gaite-lyrique.net',
    linkSrc: 'https://gaite-lyrique.net',
    pic: 'art3.jpg',
    color: '#D6B2F9',
    lat: 48.88,
    lng: 2.3652,
    isOpen: false,
    x: 610,
    y: 90,
    zIndex: 0,
    isFull: false,
  },
  {
    id: 4,
    type: 'Mode',
    desc1: '',
    desc2: '',
    address1: 'Palais de Tokyo',
    address2: '75010',
    month: 'février',
    date: ['2018', '02', '24'],
    linkText: 'www.gaite-lyrique.net',
    linkSrc: 'https://gaite-lyrique.net',
    pic: 'mode.jpg',
    color: '#edbacc',
    lat: 48.86,
    lng: 2.28,
    isOpen: false,
    x: 200,
    y: 420,
    zIndex: 0,
    isFull: false,
  },
  {
    id: 5,
    type: 'Nuit',
    desc1: '',
    desc2: '',
    address1: 'Place de Clichy',
    address2: '75018',
    month: 'octobre',
    date: ['2017', '10', '03'],
    linkText: 'www.gaite-lyrique.net',
    linkSrc: 'https://gaite-lyrique.net',
    pic: 'night.jpg',
    color: '#dbc7cf',
    lat: 48.88,
    lng: 2.32,
    isOpen: false,
    x: 100,
    y: 75,
    zIndex: 0,
    isFull: false,
  },
];
